In [1]:
import pandas as pd
from pathlib import Path

from imagematerials.vehicles.modelling_functions import interpolate
from imagematerials.util import read_circular_economy_config

In [11]:
base_dir = "../data/raw"
circular_economy_scenario_dirs = {"slow": Path(base_dir) / 'circular_economy_scenarios' / 'slow'}
circular_economy_config = read_circular_economy_config(circular_economy_scenario_dirs)

target_year = circular_economy_config['slow']['vehicles']['target_year']
base_year = circular_economy_config['slow']['vehicles']['base_year']
lifetime_increase = circular_economy_config['slow']['vehicles']['lifetime_increase_percent']

lifetimes_vehicles: pd.DataFrame = pd.read_csv("../data/raw/vehicles/SSP2_CP/lifetimes_years.csv", index_col=[
            0, 1])

lifetimes_vehicles = lifetimes_vehicles.rename_axis('mode', axis=1).stack()
lifetimes_vehicles = lifetimes_vehicles[(lifetimes_vehicles.T != 0)]
lifetimes_vehicles = lifetimes_vehicles.unstack(['mode', 'data'])
lifetimes_vehicles = interpolate(pd.DataFrame(lifetimes_vehicles))
lifetimes_vehicles

mode air_pas air_freight rail_reg rail_hst rail_freight sea_shipping_small  \
data    mean        mean     mean     mean         mean               mean
year
1807    20.0        21.0     35.0     30.0         38.0               26.0
1808    20.0        21.0     35.0     30.0         38.0               26.0
1809    20.0        21.0     35.0     30.0         38.0               26.0
1810    20.0        21.0     35.0     30.0         38.0               26.0
1811    20.0        21.0     35.0     30.0         38.0               26.0
...      ...         ...      ...      ...          ...                ...
2056    20.0        21.0     35.0     30.0         38.0               26.0
2057    20.0        21.0     35.0     30.0         38.0               26.0
2058    20.0        21.0     35.0     30.0         38.0               26.0
2059    20.0        21.0     35.0     30.0         38.0               26.0
2060    20.0        21.0     35.0     30.0         38.0               26.0

mode sea_shipping_med sea_shipping_large sea_shipping_vl   LCV  ...         \
data             mean               mean            mean  mean  ...  stdev
year                                                            ...
1807             26.0               26.0            26.0  14.0  ...  0.196
1808             26.0               26.0            26.0  14.0  ...  0.196
1809             26.0               26.0            26.0  14.0  ...  0.196
1810             26.0               26.0            26.0  14.0  ...  0.196
1811             26.0               26.0            26.0  14.0  ...  0.196
...               ...                ...             ...   ...  ...    ...
2056             26.0               26.0            26.0  14.0  ...  0.196
2057             26.0               26.0            26.0  14.0  ...  0.196
2058             26.0               26.0            26.0  14.0  ...  0.196
2059             26.0               26.0            26.0  14.0  ...  0.196
2060             26.0               26.0            26.0  14.0  ...  0.196

mode    MFT    HFT midi_bus reg_bus inland_shipping bicycle   car
data  stdev  stdev    stdev   stdev           stdev   stdev stdev shape  scale
year
1807  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
1808  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
1809  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
1810  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
1811  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
...     ...    ...      ...     ...             ...     ...   ...   ...    ...
2056  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
2057  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
2058  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
2059  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07
2060  0.266  0.266    0.322   0.322           0.266   0.266   0.4  2.01  16.07

[254 rows x 36 columns]

In [5]:
lifetime_increase

{'air_pas': 10,
 'air_freight': 10,
 'rail_reg': 38,
 'rail_hst': 38,
 'rail_freight': 38,
 'sea_shipping_small': 33,
 'sea_shipping_med': 33,
 'sea_shipping_large': 33,
 'sea_shipping_vl': 33,
 'LCV': 10,
 'MFT': 10,
 'HFT': 10,
 'midi_bus': 20,
 'reg_bus': 20,
 'inland_shipping': 33,
 'bicycle': 20,
 'car': 22.5}

In [12]:

lifetimes_vehicles = lifetimes_vehicles[lifetimes_vehicles.index <= base_year].copy()
lifetimes_vehicles.loc[target_year] = lifetimes_vehicles.loc[base_year]

for mode, increase in lifetime_increase.items():
    col = (mode, 'mean')
    if col in lifetimes_vehicles.columns:
        base_val = lifetimes_vehicles.loc[base_year, col]
        lifetimes_vehicles.loc[target_year, col] = base_val * (1 + increase / 100)
    else:
        print(f"Missing mode: {col}")
lifetimes_vehicles = interpolate(pd.DataFrame(lifetimes_vehicles))

In [13]:
lifetimes_vehicles

mode    air_pas air_freight   rail_reg   rail_hst rail_freight  \
data       mean        mean       mean       mean         mean
year
1807  20.000000   21.000000  35.000000  30.000000    38.000000
1808  20.000000   21.000000  35.000000  30.000000    38.000000
1809  20.000000   21.000000  35.000000  30.000000    38.000000
1810  20.000000   21.000000  35.000000  30.000000    38.000000
1811  20.000000   21.000000  35.000000  30.000000    38.000000
...         ...         ...        ...        ...          ...
2056  21.804878   22.895122  47.002439  40.287805    51.031220
2057  21.853659   22.946341  47.326829  40.565854    51.383415
2058  21.902439   22.997561  47.651220  40.843902    51.735610
2059  21.951220   23.048780  47.975610  41.121951    52.087805
2060  22.000000   23.100000  48.300000  41.400000    52.440000

mode sea_shipping_small sea_shipping_med sea_shipping_large sea_shipping_vl  \
data               mean             mean               mean            mean
year
1807          26.000000        26.000000          26.000000       26.000000
1808          26.000000        26.000000          26.000000       26.000000
1809          26.000000        26.000000          26.000000       26.000000
1810          26.000000        26.000000          26.000000       26.000000
1811          26.000000        26.000000          26.000000       26.000000
...                 ...              ...                ...             ...
2056          33.742927        33.742927          33.742927       33.742927
2057          33.952195        33.952195          33.952195       33.952195
2058          34.161463        34.161463          34.161463       34.161463
2059          34.370732        34.370732          34.370732       34.370732
2060          34.580000        34.580000          34.580000       34.580000

mode        LCV  ...           MFT    HFT midi_bus reg_bus inland_shipping  \
data       mean  ...  stdev  stdev  stdev    stdev   stdev           stdev
year             ...
1807  14.000000  ...  0.196  0.266  0.266    0.322   0.322           0.266
1808  14.000000  ...  0.196  0.266  0.266    0.322   0.322           0.266
1809  14.000000  ...  0.196  0.266  0.266    0.322   0.322           0.266
1810  14.000000  ...  0.196  0.266  0.266    0.322   0.322           0.266
1811  14.000000  ...  0.196  0.266  0.266    0.322   0.322           0.266
...         ...  ...    ...    ...    ...      ...     ...             ...
2056  15.263415  ...  0.196  0.266  0.266    0.322   0.322           0.266
2057  15.297561  ...  0.196  0.266  0.266    0.322   0.322           0.266
2058  15.331707  ...  0.196  0.266  0.266    0.322   0.322           0.266
2059  15.365854  ...  0.196  0.266  0.266    0.322   0.322           0.266
2060  15.400000  ...  0.196  0.266  0.266    0.322   0.322           0.266

mode bicycle   car
data   stdev stdev shape  scale
year
1807   0.266   0.4  2.01  16.07
1808   0.266   0.4  2.01  16.07
1809   0.266   0.4  2.01  16.07
1810   0.266   0.4  2.01  16.07
1811   0.266   0.4  2.01  16.07
...      ...   ...   ...    ...
2056   0.266   0.4  2.01  16.07
2057   0.266   0.4  2.01  16.07
2058   0.266   0.4  2.01  16.07
2059   0.266   0.4  2.01  16.07
2060   0.266   0.4  2.01  16.07

[254 rows x 36 columns]