In [1]:
import pandas as pd
import numpy as np
import material_intensities as mi_module

In [2]:
# Read in RASMI material intensity data and MI from old IMAGE-Materials CP
mi_rasmi = mi_module.load_mi_rasmi()
mi_image_mat = mi_module.load_mi_image_mat()

In [3]:
expand_image_mat_mi = mi_module.expand_image_mat_mi

In [4]:
# mapping dictionaries and constants (defined in material_intensities.py)
image_to_rasmi = mi_module.image_to_rasmi
image_to_material_cities = mi_module.image_to_material_cities
housing_type_image_to_rasmi = mi_module.housing_type_image_to_rasmi
housing_type_rasmi_to_image = mi_module.housing_type_rasmi_to_image
housing_type_to_rasmi_building_structure = mi_module.housing_type_to_rasmi_building_structure
material_list_rasmi = mi_module.material_list_rasmi
mis_list_target = mi_module.mis_list_target
steel_regions_adapt = mi_module.steel_regions_adapt

In [5]:
# Read in MaterialCities data, indexed by GID_0 with only the GFA_* columns kept
material_cities = mi_module.load_material_cities()

# sum GFA per IMAGE region based on image_to_material_cities
material_cities_image = mi_module.aggregate_material_cities_to_image_regions(material_cities)

# share of concrete/masonry/steel/timber per region (U excluded), for RS and RM housing types
rs_structure_shares = mi_module.structure_type_shares(material_cities_image, "RS")
rm_structure_shares = mi_module.structure_type_shares(material_cities_image, "RM")

material_cities_image

,GFA_NR_C,GFA_NR_M,GFA_NR_S,GFA_NR_T,GFA_NR_U,GFA_RS_C,GFA_RS_M,GFA_RS_S,GFA_RS_T,GFA_RS_U,GFA_RM_C,GFA_RM_M,GFA_RM_S,GFA_RM_T,GFA_RM_U
Region,,,,,,,,,,,,,,,
1.0,2.436676e+08,2.544862e+08,1.814181e+08,1.175247e+06,9.075415e+07,3.975966e+04,1.662226e+08,6.168938e+05,2.881623e+09,0.000000e+00,6.555446e+07,1.620008e+08,9.630050e+06,8.458092e+08,0.000000e+00
2.0,1.011344e+09,1.585628e+09,2.197342e+09,1.167074e+09,2.697542e+06,2.509774e+08,6.740342e+09,3.468976e+07,3.332859e+10,6.274142e+04,7.119413e+08,2.758375e+09,3.874988e+08,7.919147e+09,0.000000e+00
3.0,1.180288e+08,1.684494e+08,6.347938e+05,3.380953e+05,7.732963e+02,7.811353e+08,4.958621e+09,1.009275e+03,2.117750e+08,5.803843e+07,5.795043e+08,1.511688e+09,9.484700e+03,4.027223e+06,0.000000e+00
4.0,5.233436e+07,5.388424e+07,3.846477e+07,1.157452e+07,0.000000e+00,2.298380e+08,2.477252e+09,0.000000e+00,5.123153e+08,5.624769e+07,4.736646e+08,5.262753e+08,4.040364e+04,5.254169e+06,0.000000e+00
5.0,2.080667e+08,2.567730e+08,5.409021e+07,1.666916e+01,0.000000e+00,1.700345e+01,7.734625e+09,7.110534e+01,2.009928e+08,1.682890e+09,3.939887e+09,1.106681e+09,0.000000e+00,0.000000e+00,0.000000e+00
6.0,2.045523e+08,1.233209e+08,6.163799e+07,6.598173e+04,6.498972e+05,4.705013e+07,6.043908e+09,4.212604e+06,8.315804e+08,4.361965e+08,1.231545e+09,2.119089e+09,0.000000e+00,0.000000e+00,0.000000e+00
7.0,6.046152e+07,1.715676e+08,3.390982e+07,3.949891e+06,2.686596e+07,1.857873e+09,3.933956e+09,0.000000e+00,9.534043e+07,5.274966e+08,1.571605e+09,8.499210e+08,0.000000e+00,5.319249e+07,7.785717e+07
8.0,9.338298e+06,6.813476e+07,1.071745e+07,6.662143e+06,5.326330e+07,1.993410e+08,4.241076e+09,0.000000e+00,1.884321e+09,8.189354e+08,1.506689e+09,1.590509e+09,0.000000e+00,5.439064e+08,0.000000e+00
9.0,2.216335e+06,2.656673e+07,3.845976e+06,7.208602e+06,1.376547e+07,3.215440e+07,1.262643e+09,0.000000e+00,9.492331e+08,3.196767e+08,1.736842e+08,3.516667e+08,0.000000e+00,2.732148e+08,0.000000e+00
10.0,1.852682e+07,1.075341e+08,1.293605e+07,1.220329e+06,7.158114e+06,7.546160e+07,2.919517e+09,0.000000e+00,6.239209e+07,4.043188e+08,6.250211e+08,4.056860e+08,0.000000e+00,0.000000e+00,0.000000e+00
11.0,4.040652e+09,1.477025e+09,1.725716e+09,3.896351e+08,1.810628e+03,2.231293e+10,1.042891e+10,9.713359e+08,1.081639e+09,1.978545e+09,2.236473e+09,6.843343e+09,3.221840e+06,9.836537e+08,1.055764e+08
12.0,7.797822e+08,1.838885e+08,3.521543e+08,2.497178e+07,2.432441e+06,7.993799e+09,2.766592e+09,1.874537e+05,5.654353e+06,1.135319e+08,1.571455e+08,1.447419e+09,0.000000e+00,8.528015e+07,1.306281e+07
13.0,3.677938e+08,4.623880e+07,1.150671e+06,4.847135e+06,5.839310e+06,2.266593e+09,5.985222e+08,1.490365e+05,5.458699e+03,2.944328e+07,5.765634e+08,6.404840e+08,2.348755e+05,2.632892e+07,0.000000e+00
14.0,2.032456e+08,2.066534e+08,6.648094e+07,2.054018e+07,8.664903e+02,2.787469e+08,3.244587e+09,0.000000e+00,2.177214e+08,1.809086e+04,1.036149e+09,6.064044e+07,1.783595e+00,7.799266e+03,0.000000e+00
15.0,5.178243e+07,3.338539e+07,8.797210e+06,1.517310e+07,4.729805e+07,3.489769e+08,3.440399e+09,4.971964e+04,2.917169e+08,1.038719e+09,7.166265e+08,5.509899e+08,1.287654e+08,7.011417e+02,0.000000e+00
16.0,3.307651e+08,7.374780e+08,2.449458e+08,1.142465e+08,1.120583e+06,2.435229e+07,6.186220e+09,8.892575e+04,3.375445e+09,4.566109e+08,1.754259e+09,1.579274e+09,6.478853e+06,2.310267e+08,0.000000e+00
17.0,3.445978e+08,2.584146e+08,1.667258e+08,4.527151e+05,2.964315e+06,3.117816e+09,4.938884e+09,5.520789e+08,1.486949e+07,4.193067e+08,2.322083e+09,1.036360e+09,5.933684e+08,3.001804e+03,4.240357e+03
18.0,7.274001e+07,7.920161e+07,3.412774e+07,1.027918e+08,3.909930e+08,3.979990e+09,1.616317e+10,4.628113e+06,7.939227e+08,2.252354e+09,3.123151e+09,2.032814e+09,0.000000e+00,1.328293e+08,0.000000e+00
19.0,3.441768e+08,8.898086e+07,1.300577e+08,3.831887e+03,2.022944e+03,1.255216e+09,1.378321e+09,1.265589e+08,4.412856e+08,4.452499e+04,2.577640e+09,4.962016e+08,9.889837e+06,4.311081e+07,0.000000e+00
20.0,3.508974e+09,2.200476e+09,4.729490e+07,5.801276e+08,3.055918e+08,2.119835e+10,1.557186e+10,2.932861e+08,1.210282e+10,4.891630e+09,2.084437e+10,8.851413e+09,1.923932e+07,1.604481e+05,0.000000e+00
21.0,4.571235e+08,1.639725e+08,7.126780e+07,5.786064e+07,1.003514e+08,2.795745e+09,5.530794e+09,0.000000e+00,2.655453e+09,4.502677e+08,3.107841e+09,9.174380e+07,0.000000e+00,0.000000e+00,0.000000e+00
22.0,1.399135e+08,8.079101e+07,2.012360e+07,1.162978e+07,0.000000e+00,4.470533e+08,4.790716e+09,0.000000e+00,1.368815e+09,5.814680e+06,1.543928e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
23.0,2.540651e+08,1.710194e+06,5.075890e+08,4.798857e+07,1.859095e+06,5.774852e+08,4.712841e+07,4.856786e+08,7.404756e+09,2.846128e+06,5.455635e+09,4.136189e+06,4.457524e+08,2.772569e+08,0.000000e+00
24.0,1.934381e+08,3.419213e+07,1.016169e+08,1.363411e+07,1.787267e+06,4.475251e+07,1.158513e+09,2.260743e+06,2.004101e+09,1.443144e+07,8.713713e+08,1.862002e+08,3.445345e+06,4.226290e+08,0.000000e+00
25.0,3.600812e+07,4.062913e+07,1.064813e+07,4.116923e+06,3.591468e+05,2.404860e+08,3.602332e+09,4.371785e+08,4.430636e+08,1.962146e+08,6.375534e+08,5.981203e+08,1.383181e+03,2.400785e+07,1.249271e+07
26.0,5.203503e+06,4.658785e+07,5.577441e+06,5.185142e+06,1.891525e+07,7.972132e+07,2.253740e+09,4.103669e+02,5.809325e+08,1.872345e+08,4.240309e+08,4.754350e+08,7.505210e+01,3.543273e+07,0.000000e+00

In [6]:
rs_structure_shares

            concrete   masonry         steel    timber
Region
1.0     1.304236e-05  0.054526  2.023596e-04  0.945259
2.0     6.219299e-03  0.167028  8.596233e-04  0.825893
3.0     1.312494e-01  0.833167  1.695824e-07  0.035583
4.0     7.139145e-02  0.769475  0.000000e+00  0.159134
5.0     2.142675e-09  0.974672  8.960279e-09  0.025328
6.0     6.792525e-03  0.872546  6.081645e-04  0.120053
7.0     3.155801e-01  0.668225  0.000000e+00  0.016195
8.0     3.151766e-02  0.670554  0.000000e+00  0.297929
9.0     1.432886e-02  0.562668  0.000000e+00  0.423004
10.0    2.468186e-02  0.954911  0.000000e+00  0.020407
11.0    6.412717e-01  0.299726  2.791611e-02  0.031086
12.0    7.424880e-01  0.256969  1.741127e-05  0.000525
13.0    7.910575e-01  0.208889  5.201484e-05  0.000002
14.0    7.451024e-02  0.867292  0.000000e+00  0.058198
15.0    8.550961e-02  0.842999  1.218278e-05  0.071479
16.0    2.540373e-03  0.645332  9.276525e-06  0.352118
17.0    3.615426e-01  0.572714  6.401918e-02  0.001724
18.0    1.900509e-01  0.771817  2.209998e-04  0.037911
19.0    3.920857e-01  0.430539  3.953261e-02  0.137842
20.0    4.311559e-01  0.316718  5.965184e-03  0.246161
21.0    2.545754e-01  0.503624  0.000000e+00  0.241801
22.0    6.766784e-02  0.725143  0.000000e+00  0.207190
23.0    6.781937e-02  0.005535  5.703768e-02  0.869608
24.0    1.394321e-02  0.360949  7.043631e-04  0.624403
25.0    5.091741e-02  0.762711  9.256255e-02  0.093809
26.0    2.735434e-02  0.773313  1.408069e-07  0.199332

In [7]:
rm_structure_shares

        concrete   masonry         steel        timber
Region
1.0     0.060531  0.149586  8.892058e-03  7.809912e-01
2.0     0.060452  0.234218  3.290312e-02  6.724270e-01
3.0     0.276583  0.721491  4.526809e-06  1.922092e-03
4.0     0.471198  0.523535  4.019325e-05  5.226809e-03
5.0     0.780706  0.219294  0.000000e+00  0.000000e+00
6.0     0.367556  0.632444  0.000000e+00  0.000000e+00
7.0     0.635064  0.343441  0.000000e+00  2.149436e-02
8.0     0.413800  0.436820  0.000000e+00  1.493795e-01
9.0     0.217495  0.440373  0.000000e+00  3.421319e-01
10.0    0.606400  0.393600  0.000000e+00  0.000000e+00
11.0    0.222166  0.679801  3.200496e-04  9.771371e-02
12.0    0.092994  0.856540  0.000000e+00  5.046628e-02
13.0    0.463620  0.515019  1.888657e-04  2.117135e-02
14.0    0.944704  0.055289  1.626185e-09  7.110948e-06
15.0    0.513202  0.394584  9.221354e-02  5.021130e-07
16.0    0.491246  0.442245  1.814277e-03  6.469454e-02
17.0    0.587599  0.262249  1.501509e-01  7.596014e-07
18.0    0.590522  0.384362  0.000000e+00  2.511524e-02
19.0    0.824359  0.158691  3.162883e-03  1.378733e-02
20.0    0.701472  0.297875  6.474575e-04  5.399534e-06
21.0    0.971326  0.028674  0.000000e+00  0.000000e+00
22.0    1.000000  0.000000  0.000000e+00  0.000000e+00
23.0    0.882392  0.000669  7.209578e-02  4.484340e-02
24.0    0.587318  0.125502  2.322216e-03  2.848584e-01
25.0    0.506122  0.474818  1.098039e-06  1.905865e-02
26.0    0.453558  0.508542  8.027833e-08  3.790008e-02

In [8]:
# weighted average structure-type share actually applied, per region and per IMAGE housing type
effective_structure_weights = mi_module.effective_structure_weights

for housingtype_image, allowed_structures in housing_type_to_rasmi_building_structure.items():
    housingtype_rasmi = housing_type_image_to_rasmi[housingtype_image]
    shares = rs_structure_shares if housingtype_rasmi == "RS" else rm_structure_shares
    weights = effective_structure_weights(shares, allowed_structures)
    print(f"Housing type {housingtype_image} ({housingtype_rasmi}, allowed structures: {allowed_structures})")
    display(weights)

Housing type 1 (RS, allowed structures: ['C', 'M', 'S', 'T'])

                   C         M             S         T
Region
1.0     1.304236e-05  0.054526  2.023596e-04  0.945259
2.0     6.219299e-03  0.167028  8.596233e-04  0.825893
3.0     1.312494e-01  0.833167  1.695824e-07  0.035583
4.0     7.139145e-02  0.769475  0.000000e+00  0.159134
5.0     2.142675e-09  0.974672  8.960279e-09  0.025328
6.0     6.792525e-03  0.872546  6.081645e-04  0.120053
7.0     3.155801e-01  0.668225  0.000000e+00  0.016195
8.0     3.151766e-02  0.670554  0.000000e+00  0.297929
9.0     1.432886e-02  0.562668  0.000000e+00  0.423004
10.0    2.468186e-02  0.954911  0.000000e+00  0.020407
11.0    6.412717e-01  0.299726  2.791611e-02  0.031086
12.0    7.424880e-01  0.256969  1.741127e-05  0.000525
13.0    7.910575e-01  0.208889  5.201484e-05  0.000002
14.0    7.451024e-02  0.867292  0.000000e+00  0.058198
15.0    8.550961e-02  0.842999  1.218278e-05  0.071479
16.0    2.540373e-03  0.645332  9.276525e-06  0.352118
17.0    3.615426e-01  0.572714  6.401918e-02  0.001724
18.0    1.900509e-01  0.771817  2.209998e-04  0.037911
19.0    3.920857e-01  0.430539  3.953261e-02  0.137842
20.0    4.311559e-01  0.316718  5.965184e-03  0.246161
21.0    2.545754e-01  0.503624  0.000000e+00  0.241801
22.0    6.766784e-02  0.725143  0.000000e+00  0.207190
23.0    6.781937e-02  0.005535  5.703768e-02  0.869608
24.0    1.394321e-02  0.360949  7.043631e-04  0.624403
25.0    5.091741e-02  0.762711  9.256255e-02  0.093809
26.0    2.735434e-02  0.773313  1.408069e-07  0.199332

Housing type 2 (RS, allowed structures: ['C', 'M', 'S', 'T'])

                   C         M             S         T
Region
1.0     1.304236e-05  0.054526  2.023596e-04  0.945259
2.0     6.219299e-03  0.167028  8.596233e-04  0.825893
3.0     1.312494e-01  0.833167  1.695824e-07  0.035583
4.0     7.139145e-02  0.769475  0.000000e+00  0.159134
5.0     2.142675e-09  0.974672  8.960279e-09  0.025328
6.0     6.792525e-03  0.872546  6.081645e-04  0.120053
7.0     3.155801e-01  0.668225  0.000000e+00  0.016195
8.0     3.151766e-02  0.670554  0.000000e+00  0.297929
9.0     1.432886e-02  0.562668  0.000000e+00  0.423004
10.0    2.468186e-02  0.954911  0.000000e+00  0.020407
11.0    6.412717e-01  0.299726  2.791611e-02  0.031086
12.0    7.424880e-01  0.256969  1.741127e-05  0.000525
13.0    7.910575e-01  0.208889  5.201484e-05  0.000002
14.0    7.451024e-02  0.867292  0.000000e+00  0.058198
15.0    8.550961e-02  0.842999  1.218278e-05  0.071479
16.0    2.540373e-03  0.645332  9.276525e-06  0.352118
17.0    3.615426e-01  0.572714  6.401918e-02  0.001724
18.0    1.900509e-01  0.771817  2.209998e-04  0.037911
19.0    3.920857e-01  0.430539  3.953261e-02  0.137842
20.0    4.311559e-01  0.316718  5.965184e-03  0.246161
21.0    2.545754e-01  0.503624  0.000000e+00  0.241801
22.0    6.766784e-02  0.725143  0.000000e+00  0.207190
23.0    6.781937e-02  0.005535  5.703768e-02  0.869608
24.0    1.394321e-02  0.360949  7.043631e-04  0.624403
25.0    5.091741e-02  0.762711  9.256255e-02  0.093809
26.0    2.735434e-02  0.773313  1.408069e-07  0.199332

Housing type 3 (RM, allowed structures: ['C', 'S'])

               C             S
Region
1.0     0.871914  1.280856e-01
2.0     0.647549  3.524510e-01
3.0     0.999984  1.636665e-05
4.0     0.999915  8.529282e-05
5.0     1.000000  0.000000e+00
6.0     1.000000  0.000000e+00
7.0     1.000000  0.000000e+00
8.0     1.000000  0.000000e+00
9.0     1.000000  0.000000e+00
10.0    1.000000  0.000000e+00
11.0    0.998561  1.438517e-03
12.0    1.000000  0.000000e+00
13.0    0.999593  4.072056e-04
14.0    1.000000  1.721370e-09
15.0    0.847686  1.523144e-01
16.0    0.996320  3.679624e-03
17.0    0.796475  2.035254e-01
18.0    1.000000  0.000000e+00
19.0    0.996178  3.822115e-03
20.0    0.999078  9.221471e-04
21.0    1.000000  0.000000e+00
22.0    1.000000  0.000000e+00
23.0    0.924467  7.553349e-02
24.0    0.996062  3.938363e-03
25.0    0.999998  2.169509e-06
26.0    1.000000  1.769968e-07

Housing type 4 (RM, allowed structures: ['C', 'S'])

               C             S
Region
1.0     0.871914  1.280856e-01
2.0     0.647549  3.524510e-01
3.0     0.999984  1.636665e-05
4.0     0.999915  8.529282e-05
5.0     1.000000  0.000000e+00
6.0     1.000000  0.000000e+00
7.0     1.000000  0.000000e+00
8.0     1.000000  0.000000e+00
9.0     1.000000  0.000000e+00
10.0    1.000000  0.000000e+00
11.0    0.998561  1.438517e-03
12.0    1.000000  0.000000e+00
13.0    0.999593  4.072056e-04
14.0    1.000000  1.721370e-09
15.0    0.847686  1.523144e-01
16.0    0.996320  3.679624e-03
17.0    0.796475  2.035254e-01
18.0    1.000000  0.000000e+00
19.0    0.996178  3.822115e-03
20.0    0.999078  9.221471e-04
21.0    1.000000  0.000000e+00
22.0    1.000000  0.000000e+00
23.0    0.924467  7.553349e-02
24.0    0.996062  3.938363e-03
25.0    0.999998  2.169509e-06
26.0    1.000000  1.769968e-07

In [9]:
replace_old_mis_with_rasmi = mi_module.replace_old_mis_with_rasmi

In [10]:
# execute the function to replace old mis with rasmi values
test = replace_old_mis_with_rasmi(mi_image_mat, mi_rasmi, material_list_rasmi, rs_structure_shares, rm_structure_shares)

steel steel
concrete concrete

done
done
done
done
wood wood
copper copper

aluminium aluminum
glass glass

brick brick
done

In [11]:
test.query("Region == 20")

                               steel     concrete       wood    copper  \
Year Region Building_type
2020 20     1              17.922606  1603.555708  33.920764  0.182895
            2              17.922606  1603.555708  33.920764  0.182895
            3              46.622500  2069.149123  21.800184  0.182895
            4              46.622500  2069.149123  21.800184  0.182895
2050 20     1              17.922606  1603.555708  33.920764  0.182895
            2              17.922606  1603.555708  33.920764  0.182895
            3              46.622500  2069.149123  21.800184  0.182895
            4              46.622500  2069.149123  21.800184  0.182895

                           aluminium     glass       brick
Year Region Building_type
2020 20     1               0.491319  1.984856  339.533206
            2               0.491319  1.984856  339.533206
            3               0.493056  2.000000  191.105377
            4               0.493056  2.000000  191.105377
2050 20     1               0.491319  1.984856  339.533206
            2               0.491319  1.984856  339.533206
            3               0.493056  2.000000  191.105377
            4               0.493056  2.000000  191.105377

In [12]:
replace_old_mis_with_rasmi_resource_efficient = mi_module.replace_old_mis_with_rasmi_resource_efficient

In [13]:
mi_image_mat = expand_image_mat_mi(mi_image_mat)
test = replace_old_mis_with_rasmi_resource_efficient(mi_image_mat, mi_rasmi, material_list_rasmi, rs_structure_shares, rm_structure_shares)

steel steel
2020

2030

2050

concrete concrete
2020
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back

switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
2030
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient

switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
2050

wood wood
2020
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back

switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
2030
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient

switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
2050

copper copper
2020
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back

switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
2030
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient

switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
2050

aluminium aluminum
2020
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back

switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
2030
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient

switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
2050

glass glass
2020
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back

switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
2030
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
2050

brick brick
2020
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
switch back
2030
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient

switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
switch to more efficient
2050
done