In [ ]:
from imagematerials.rest_of.sankey_function import create_node_dict, index_mapper, convert_index_to_node_id, prepare_Sankey_lists
from imagematerials.rest_of.fossil_fuels import *                                                                                            
from imagematerials.read_mym import read_mym_df

from imagematerials.rest_of.const import path_scenario_data_fossil, DIM2_primary_dict

In [89]:
def read_in_data(scenario: str):
    # Total Primary Energy Supply (TPES) in PJ per region by energy carrier, [NRCT, PRIM + 4](t), [28,13](t), # unit: PJ
    primary_energy_supply = read_mym_df(path_input_data.joinpath(scenario, 'EnergyFlows/tpes_ext.out')).set_index(["time", "DIM_1"])
    # Primary to Secondary energy flows DIM_1:Primary, DIM_2:Secondary GJ/yr
    prim_per_sec = read_mym_df(path_input_data.joinpath(scenario, 'EnergyFlows/PrimPerSec.out')).set_index(["time", "DIM_1", "DIM_2"])
    # Final Energy in PJ/yr by region, sector, and energy carrier [NRCT, S, NECS9T](t), [28,8,10](t) # PJ
    final_energy = read_mym_df(path_input_data.joinpath(scenario, 'EnergyFlows/final_energy_rt.out')).set_index(["time", "DIM_1", "DIM_2"])

    # Deal with the index and columns of all
    # Total Primary Energy Supply (TPES) in PJ/yr
    # TODO: region 27 has some values? Why? it is not exactly the sum of sth...
    primary_energy_supply = primary_energy_supply.T  # transpose to make DIM_2 the index (DIM_1 is regions, make this columns)
    primary_energy_supply = primary_energy_supply.stack('time')  # add years as index
    primary_energy_supply = primary_energy_supply.swaplevel()  # make years the first index
    primary_energy_supply = primary_energy_supply.sort_index()  # sort dataframe based on the index
    primary_energy_supply.index.names = ['time','primary_energy']
    # drop 27 and 28 regions from columns
    primary_energy_supply = primary_energy_supply.drop(columns=[27, 28])  # drop regions 27 and 28 if they exist
    # convert DIM_2 index numbers to energy carriers names with dict
    # Reverse the dict: number -> name
    dim2_reverse = {v: k for k, v in DIM2_primary_dict.items()}

    # If DIM2 is in the index:
    primary_energy_supply.index = primary_energy_supply.index.set_levels(
        primary_energy_supply.index.levels[primary_energy_supply.index.names.index('primary_energy')].map(dim2_reverse),
        level='primary_energy'
    )


   
    return primary_energy_supply, prim_per_sec, final_energy

In [90]:
primary_energy_supply, prim_per_sec, final_energy = read_in_data("SSP2_CP")  # replace with your scenario

C:\Users\Arp00003\AppData\Local\Temp\ipykernel_3768\2613512188.py:13: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  primary_energy_supply = primary_energy_supply.stack('time')  # add years as index

In [91]:
primary_energy_supply

DIM_1                           1            2             3             4   \
time primary_energy
1971 coal                 698.0271  12522.50000     62.545410      6.109577
     oil                 3249.8190  30837.14000   1112.698000   1314.193000
     nan                    0.0000      0.00000      0.000000      0.000000
     natural gas         1089.0570  19398.21000    372.630400     67.445760
     modern biofuel         0.0000      0.00000      0.000000      0.000000
...                            ...          ...           ...           ...
2100 solar PV            1317.0720  10518.99000   3482.165000   1165.722000
     wind                2027.2930   9506.38800   1286.240000    649.070900
     other renewables     113.8944    112.90520    215.670000    269.212000
     hydro electricity    639.7349     13.43455      5.291054     29.729080
     total              12037.4500  68972.36000  16070.150000  12709.050000

DIM_1                            5           6            7              8   \
time primary_energy
1971 coal                 106.85150    192.3425     40.05804      12.624920
     oil                 1141.50700   2572.9760    589.32530     372.332000
     nan                    0.00000      0.0000      0.00000       0.000000
     natural gas            6.42315    648.7023    184.52220       4.185012
     modern biofuel         0.00000      0.0000      0.00000       0.000000
...                             ...         ...          ...            ...
2100 solar PV            5884.58200   3280.9690   8570.71800   22242.700000
     wind                4416.85900   3906.3540   3317.08400    7959.845000
     other renewables       0.00048    340.3232     39.79800       0.005738
     hydro electricity   2534.36300   2370.5930     23.08436    1453.621000
     total              32797.46000  27624.1900  38563.09000  106826.000000

DIM_1                             9            10  ...            17  \
time primary_energy                                ...
1971 coal                   2.423960  1654.349000  ...      9.633130
     oil                  224.370900   522.470800  ...   2467.381000
     nan                    0.000000     0.000000  ...      0.000000
     natural gas            0.004345     0.859017  ...    620.730300
     modern biofuel         0.000000     0.000000  ...      0.000000
...                              ...          ...  ...           ...
2100 solar PV           11166.020000   996.000900  ...  13612.310000
     wind                5173.445000  1267.983000  ...   3543.461000
     other renewables    1972.157000   256.108400  ...      0.405584
     hydro electricity    319.464000    30.102670  ...     15.411200
     total              46170.370000  8635.906000  ...  59048.910000

DIM_1                             18           19             20           21  \
time primary_energy
1971 coal                 1303.67500   944.474500    6312.123000    212.05430
     oil                   860.34010   482.178800    2319.794000   1414.14300
     nan                     0.00000     0.000000       0.000000      0.00000
     natural gas            32.37033     1.719365     159.578600     11.59313
     modern biofuel          0.00000     0.000000       0.000000      0.00000
...                              ...          ...            ...          ...
2100 solar PV            16558.21000   323.211700   12149.670000   5358.75300
     wind                 4819.39600   213.265000   14114.640000   2078.85000
     other renewables       76.70958    11.141060       1.717159    353.93620
     hydro electricity     120.18070     3.191360    4095.674000    111.66350
     total              134975.20000  7040.691000  113190.600000  53848.05000

DIM_1                             22           23           24           25  \
time primary_energy
1971 coal                   8.864608   2144.71200    910.02450     52.13260
     oil                  472.028300   9644.69100   1378.88000    351.32540
     nan                    0.000000      0.00000      0.00000      0.00000
     natural gas            2.917993    249.36490    102.58840    121.95230
     modern biofuel         0.000000      0.00000      0.00000      0.00000
...                              ...          ...          ...          ...
2100 solar PV            2709.351000    631.93270   2027.65700  12871.55000
     wind                1010.238000    246.61470   3033.47000   3403.57700
     other renewables     953.655500    134.21650     79.25272     30.45985
     hydro electricity    153.013700     53.20102     33.76656    352.68900
     total              34074.630000  11671.44000  11989.72000  89655.94000

DIM_1                             26
time primary_energy
1971 coal                 107.558600
     oil                  167.503100
     nan                    0.000000
     natural gas            1.876137
     modern biofuel         0.000000
...                              ...
2100 solar PV            7765.028000
     wind                3604.285000
     other renewables     330.256500
     hydro electricity    239.648200
     total              41336.320000

[1690 rows x 26 columns]

In [15]:
# -*- coding: utf-8 -*-
"""
Created on Tue May  7 13:15:30 2024

@author: Arp00003
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import plotly.graph_objects as go

from imagematerials.read_mym import read_mym_df
from imagematerials.rest_of.const import (parse_dim, get_key, DIM2_primary_dict, 
                                          path_figures, path_input_data)

from imagematerials.rest_of.sankey_function import create_node_dict, index_mapper, convert_index_to_node_id, prepare_Sankey_lists

coal_conversion = 28.9 # coal: 28.9 MJ/kg Coal (low bituminous)
oil_conversion = 45.5 # oil: 45.5 MJ/kg Crude oil
gas_conversion = 52.2 # gas: 52.2 MJ/kg Natural gas (95% methane)

mega_to_peta = 1e9
giga_to_peta = 1e6

#%% Primary energy from Joule to kg
def converte_primary_energy_to_mass(fossils_primary):
    coal_converted = fossils_primary.query(parse_dim('primary', '2', 'coal')) * mega_to_peta / coal_conversion
    oil_converted = fossils_primary.query(parse_dim('primary', '2', 'oil')) * mega_to_peta / oil_conversion
    gas_converted = fossils_primary.query(parse_dim('primary', '2', 'natural gas')) * mega_to_peta / gas_conversion
    
    fossils_primary_converteted = pd.concat([coal_converted, oil_converted, gas_converted])
    
    return fossils_primary_converteted




def convert_primary_to_secondary_to_mass(fossils_prim_per_sec):
    coal_converted = fossils_prim_per_sec.query(parse_dim('primsec_reversed', '1', 'coal')) * mega_to_peta / coal_conversion
    conv_oil_converted = fossils_prim_per_sec.query(parse_dim('primsec_reversed', '1', 'conventional oil')) * mega_to_peta / oil_conversion
    unconv_oil_converted = fossils_prim_per_sec.query(parse_dim('primsec_reversed', '1', 'unconventional oil')) * mega_to_peta / oil_conversion
    gas_converted = fossils_prim_per_sec.query(parse_dim('primsec_reversed', '1', 'natural gasses')) * mega_to_peta / gas_conversion
    
    fossils_primsecond_converted = pd.concat([coal_converted, conv_oil_converted, unconv_oil_converted, gas_converted])
    
    return fossils_primsecond_converted
    


def convert_secondary_to_final_mass(fossils_final):
    coal_converted = fossils_final.query(parse_dim('seconden_reversed', '3', 'coal')) * mega_to_peta / coal_conversion
    coal_converted.drop(columns=[27, 28], inplace=True)  # drop 27 and 28, which are empty regions & global region

    heavy_oil_converted = fossils_final.query(parse_dim('seconden_reversed', '3', 'heavy oil')) * mega_to_peta / oil_conversion
    heavy_oil_converted.drop(columns=[27, 28], inplace=True)  

    light_oil_converted = fossils_final.query(parse_dim('seconden_reversed', '3', 'light oil')) * mega_to_peta / oil_conversion
    light_oil_converted.drop(columns=[27, 28], inplace=True)

    gas_converted = fossils_final.query(parse_dim('seconden_reversed', '3', 'natural gas')) * mega_to_peta / gas_conversion
    gas_converted.drop(columns=[27, 28], inplace=True)

    return {'coal': coal_converted, 
            'heavy oil': heavy_oil_converted, 
            'light oil': light_oil_converted, 
            'natural gas': gas_converted }



def fossil_fuel_data(scenario):
    # https://www.engineeringtoolbox.com/fossil-fuels-energy-content-d_1298.html
    # read in and format relevant IMAGE data

    # Total Primary Energy Supply (TPES) in PJ per region by energy carrier, [NRCT, PRIM + 4](t), [28,13](t), # unit: PJ
    primary_energy_supply = read_mym_df(path_input_data.joinpath(scenario, 'EnergyFlows/tpes_ext.out')).set_index(["time", "DIM_1"])
    # Primary to Secondary energy flows DIM_1:Primary, DIM_2:Secondary GJ/yr
    prim_per_sec = read_mym_df(path_input_data.joinpath(scenario, 'EnergyFlows/PrimPerSec.out')).set_index(["time", "DIM_1", "DIM_2"])
    # Final Energy in PJ/yr by region, sector, and energy carrier [NRCT, S, NECS9T](t), [28,8,10](t) # PJ
    final_energy = read_mym_df(path_input_data.joinpath(scenario, 'EnergyFlows/final_energy_rt.out')).set_index(["time", "DIM_1", "DIM_2"])  

    # Total Primary Energy Supply (TPES) in PJ/yr
    # TODO: region 27 has some values? Why? it is not exactly the sum of sth...
    primary_energy_supply = primary_energy_supply.T  # transpose to make DIM_2 the index (DIM_1 is regions, make this columns)
    primary_energy_supply = primary_energy_supply.stack('time')  # add years as index
    primary_energy_supply = primary_energy_supply.swaplevel()  # make years the first index
    primary_energy_supply = primary_energy_supply.sort_index()  # sort dataframe based on the index
    primary_energy_supply.index.names = ['time','DIM_2']

    # Primary to Secondary energy flows in GJ/yr
    prim_per_sec = prim_per_sec/giga_to_peta # GJ to PJ
    prim_per_sec = prim_per_sec.rename(columns={27: 28}) # rename 27 to 28 to fit other dfs
    prim_per_sec[27] = np.nan # create empty dummy 27 region
    prim_per_sec = prim_per_sec[sorted(prim_per_sec.columns)] # sort so that 27 is before 28

    # Final Energy in PJ/yr 
    #TODO: region 27 is empty
    final_energy = final_energy.T # transpose to make DIM_1 the index
    final_energy = final_energy.stack(['time', 'DIM_2'])  # add years as and DIM_2 index
    final_energy.index.names = ['DIM_3', 'time', 'DIM_2']
    final_energy = final_energy.swaplevel(0, 1)  # make years the first index

    #%% Fossil energy only

    fossils_primary = primary_energy_supply.query(parse_dim('primary', '2', 'coal' ,'oil', 
                                                    'natural gas'))
    fossils_prim_per_sec = prim_per_sec.query(parse_dim('primsec_reversed', '1', 'coal', 
                                                'conventional oil', 'unconventional oil', 
                                                'natural gasses'))
    fossils_final = final_energy.query(parse_dim('seconden_reversed', '3', 'coal',
                                            'heavy oil', 'light oil', 'natural gas'))
    
    fossils_primary_converted = converte_primary_energy_to_mass(fossils_primary)
    fossils_primsecond_converted = convert_primary_to_secondary_to_mass(fossils_prim_per_sec)
    fossils_final_converteted = convert_secondary_to_final_mass(fossils_final)

    return_dict = {
        'fossils_primary': fossils_primary,
        'fossils_prim_per_sec': fossils_prim_per_sec,
        'fossils_final': fossils_final,
        'fossils_primary_converted': fossils_primary_converted,
        'fossils_primsecond_converted': fossils_primsecond_converted,
        'fossils_final_converteted': fossils_final_converteted
    }

    return return_dict

In [16]:
#%% Plot primary energy of selected region (in joule or kg)

def plot_stacked_fossils(country_id: int, fossils_primary: pd.DataFrame, unit: str):
    fossils_primary_region = fossils_primary.loc[:, country_id].unstack() # unstacks second index (primary energy types)
    
    fig, ax = plt.subplots(figsize=(15, 10))
    # fossils_primary_region.plot(kind='area', ax=ax)
    
    # define labels via dict
    labels = [get_key(i, DIM2_primary_dict) for i in list(fossils_primary_region.columns)]
    
    # Add labels and title
    ax.stackplot(fossils_primary_region.index, 
                 fossils_primary_region.loc[:, 1], 
                 fossils_primary_region.loc[:, 2], 
                 fossils_primary_region.loc[:, 4],
                 labels = labels)
    
    # .rename(get_key(1, DIM2_primary_dict))
    ax.legend(loc='upper left')
    ax.set_xlabel('Years')
    ax.set_ylabel(f'Fossil energy [{unit}]')
    
    plt.xlim(left=1971, right=2100)
    fig.tight_layout()

#%% plot primary per secondary sankey

In [17]:
def plot_fossils_sankey(year: int, country_id: int, df1: pd.DataFrame, 
                        df2: pd.DataFrame, DIM1_primsec_dict, DIM2_primsec_dict, 
                        DIM3_seconden_dict, DIM2_sectors_dict, unit: str):

    # Create nodes
    energy_sources = [*DIM1_primsec_dict.values(), *DIM2_primsec_dict.values(),
                      *DIM3_seconden_dict.values(), *DIM2_sectors_dict.values()
                      ]  # * flattens the dict_keys objects
    nodes = create_node_dict(energy_sources)
    
    # Prepare dataframes
    # Get "real" name of energy sources instead of their numbers
    fossils_prim_per_sec_sankey = df1.loc[year, country_id].copy()
    fossils_prim_per_sec_sankey.index = fossils_prim_per_sec_sankey.index.map(index_mapper(
        DIM1_primsec_dict.get,
        DIM2_primsec_dict.get
    ))
    
    fossils_final_energy_sankey = df2.loc[year, country_id].copy()
    fossils_final_energy_sankey.index = fossils_final_energy_sankey.index.map(index_mapper(
        DIM3_seconden_dict.get,
        DIM2_sectors_dict.get
    ))
    
    # Drop where either dimension is "total"
    is_total = fossils_prim_per_sec_sankey.index.get_level_values(0).isin(["total"]) | fossils_prim_per_sec_sankey.index.get_level_values(1).isin(["total"])
    fossils_prim_per_sec_sankey = fossils_prim_per_sec_sankey[~is_total]
    
    is_total = fossils_final_energy_sankey.index.get_level_values(0).isin(["total"]) | fossils_final_energy_sankey.index.get_level_values(1).isin(["total"])
    fossils_final_energy_sankey = fossils_final_energy_sankey[~is_total]
    
    # Convert "real" names to unique node identifiers
    convert_index_to_node_id(fossils_prim_per_sec_sankey, nodes)
    convert_index_to_node_id(fossils_final_energy_sankey, nodes)
    
    # Prepare lists for Sankey diagram
    link_source, link_target, link_value = prepare_Sankey_lists(fossils_prim_per_sec_sankey)
    prepare_Sankey_lists(fossils_final_energy_sankey, link_source, link_target, link_value)
    
    # Create Sankey diagram
    fig = go.Figure(data=[go.Sankey( 
        node = dict( 
          thickness = 5, 
          line = dict(color = "green", width = 0.1), 
          label = list(nodes.keys()), 
          color = "blue"
        ), 
        link = dict(
            source = link_source,  
            target = link_target, 
            value = link_value
      ))]) 
    
    # fig.write_image("figures/energy_sankey.jpg")
    fig.write_html(f"{path_figures}/fossils_global_{unit}.html")

In [18]:
# # https://www.engineeringtoolbox.com/fossil-fuels-energy-content-d_1298.html



# #%% read in and format relevant IMAGE data

# # Total Primary Energy Supply (TPES) in PJ per region by energy carrier, [NRCT, PRIM + 4](t), [28,13](t), # unit: PJ
# primary_energy_supply = read_mym_df(f'{path_scenario_data_fossil}/tpes_ext.out').set_index(["time", "DIM_1"])
# # Primary to Secondary energy flows DIM_1:Primary, DIM_2:Secondary GJ/yr
# prim_per_sec = read_mym_df(f'{path_scenario_data_fossil}/PrimPerSec.out').set_index(["time", "DIM_1", "DIM_2"])
# # Final Energy in PJ/yr by region, sector, and energy carrier [NRCT, S, NECS9T](t), [28,8,10](t) # PJ
# final_energy = read_mym_df(f'{path_scenario_data_fossil}/final_energy_rt.out').set_index(["time", "DIM_1", "DIM_2"])  

# # Total Primary Energy Supply (TPES) in PJ/yr
# # TODO: region 27 has some values? Why? it is not exactly the sum of sth...
# primary_energy_supply = primary_energy_supply.T  # transpose to make DIM_2 the index (DIM_1 is regions, make this columns)
# primary_energy_supply = primary_energy_supply.stack('time')  # add years as index
# primary_energy_supply = primary_energy_supply.swaplevel()  # make years the first index
# primary_energy_supply = primary_energy_supply.sort_index()  # sort dataframe based on the index
# primary_energy_supply.index.names = ['time','DIM_2']

# # Primary to Secondary energy flows in GJ/yr
# prim_per_sec = prim_per_sec/giga_to_peta # GJ to PJ
# prim_per_sec = prim_per_sec.rename(columns={27: 28}) # rename 27 to 28 to fit other dfs
# prim_per_sec[27] = np.nan # create empty dummy 27 region
# prim_per_sec = prim_per_sec[sorted(prim_per_sec.columns)] # sort so that 27 is before 28

# # Final Energy in PJ/yr 
# #TODO: region 27 is empty
# final_energy = final_energy.T # transpose to make DIM_1 the index
# final_energy = final_energy.stack(['time', 'DIM_2'])  # add years as and DIM_2 index
# final_energy.index.names = ['DIM_3', 'time', 'DIM_2']
# final_energy = final_energy.swaplevel(0, 1)  # make years the first index

# #%% Fossil energy only

# fossils_primary = primary_energy_supply.query(parse_dim('primary', '2', 'coal' ,'oil', 
#                                                         'natural gas'))
# fossils_prim_per_sec = prim_per_sec.query(parse_dim('primsec_reversed', '1', 'coal', 
#                                                     'conventional oil', 'unconventional oil', 
#                                                     'natural gasses'))
# fossils_final = final_energy.query(parse_dim('seconden_reversed', '3', 'coal',
#                                              'heavy oil', 'light oil', 'natural gas'))

In [19]:
fossil_fuel_data = fossil_fuel_data("SSP2_CP")  # replace with your scenario

C:\Users\Arp00003\AppData\Local\Temp\ipykernel_3768\1937868047.py:86: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  primary_energy_supply = primary_energy_supply.stack('time')  # add years as index
C:\Users\Arp00003\AppData\Local\Temp\ipykernel_3768\1937868047.py:100: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  final_energy = final_energy.stack(['time', 'DIM_2'])  # add years as and DIM_2 index

In [20]:
fossil_fuel_data

{'fossils_primary': DIM_1              1           2           3            4            5   \
 time DIM_2
 1971 1       698.0271  12522.5000    62.54541     6.109577    106.85150
      2      3249.8190  30837.1400  1112.69800  1314.193000   1141.50700
      4      1089.0570  19398.2100   372.63040    67.445760      6.42315
 1972 1       617.3547  13549.5400    69.98534     6.253846    113.25750
      2      3415.9660  32561.9600  1222.90100  1378.695000   1262.60300
 ...               ...         ...         ...          ...          ...
 2099 2      1855.2090  12523.6100  3219.88300  1786.765000   4248.85000
      4      5651.6480  31496.9000  5692.82500  3023.600000  13905.74000
 2100 1       117.7780    251.0827   834.22810  3783.747000    226.53780
      2      1850.7760  12439.3400  3155.66300  1777.086000   4176.35600
      4      5557.0410  30904.0900  5611.31600  3063.398000  13776.55000

 DIM_1               6            7             8             9            10  \
 time DIM_2
 1971 1        192.3425     40.05804     12.624920      2.423960  1654.349000
      2       2572.9760    589.32530    372.332000    224.370900   522.470800
      4        648.7023    184.52220      4.185012      0.004345     0.859017
 1972 1        177.6139     43.44423     14.271270      1.454079  1725.818000
      2       2697.2700    650.30710    397.222400    234.483700   494.237600
 ...                ...          ...           ...           ...          ...
 2099 2       3753.9140   7439.53200  10826.870000   5470.202000  1666.428000
      4      10946.0500  18451.48000  45748.770000  14029.650000  1742.127000
 2100 1        385.3138    100.31680   4780.029000    929.504300  1926.251000
      2       3677.4910   7418.21200  10920.920000   5373.724000  1639.879000
      4      11107.1700  18127.95000  45512.550000  14642.380000  1789.079000

 DIM_1       ...           19          20           21            22  \
 time DIM_2  ...
 1971 1      ...   944.474500   6312.1230    212.05430      8.864608
      2      ...   482.178800   2319.7940   1414.14300    472.028300
      4      ...     1.719365    159.5786     11.59313      2.917993
 1972 1      ...   997.676200   6521.4640     82.56240      8.490191
      2      ...   493.645800   2498.5100   1518.80500    536.274400
 ...         ...          ...         ...          ...           ...
 2099 2      ...   498.735700  16049.5500   8508.65100   6263.456000
      4      ...  3748.070000  36629.7800  11097.02000   6228.196000
 2100 1      ...   567.280200  13336.4900  16969.77000  13777.470000
      2      ...   501.455000  15720.4600   8387.86400   6174.729000
      4      ...  3739.014000  36103.4000  10883.04000   6143.432000

 DIM_1              23          24           25            26   27         28
 time DIM_2
 1971 1      2144.7120   910.02450     52.13260    107.558600  0.0   59549.50
      2      9644.6910  1378.88000    351.32540    167.503100  0.0  102575.70
      4       249.3649   102.58840    121.95230      1.876137  0.0   41391.29
 1972 1      2196.3200   977.21650     51.60107    103.923200  0.0   60013.69
      2      9969.4640  1403.68600    337.24800    173.044400  0.0  108165.70
 ...               ...         ...          ...           ...  ...        ...
 2099 2       882.1475   630.93150   9707.97400   7640.884000  0.0  158254.50
      4      2790.9950  4041.81500  34106.36000  15592.210000  0.0  378262.80
 2100 1      2748.2480    88.91495  17923.55000    416.145100  0.0  132123.40
      2       903.1907   631.10660   9737.72500   7688.304000  0.0  157048.00
      4      2761.5940  4024.90600  34005.52000  15869.810000  0.0  376250.40

 [390 rows x 28 columns],
 'fossils_prim_per_sec':                         1           2           3            4           5   \
 time DIM_1 DIM_2
 1971 1     1      214.4967   3702.1660    48.01503     6.188289    29.61583
            2        0.0000      0.0000     0.00000     0.000000     0.00000
            3        0.0000      0.0000     0.00000     0.000000     0.00000
            4        0.0000      0.0000     0.00000     0.000000     0.00000
            5        0.0000      0.0000     0.00000     0.000000     0.00000
 ...                    ...         ...         ...          ...         ...
 2100 4     5        0.0000      0.0000     0.00000     0.000000     0.00000
            6       61.3523    208.0908     1.82296     0.951860     0.46139
            7        0.0000      0.0000     0.00000     0.000000     0.00000
            8      440.3695  15789.5000  3574.17600  1794.849000  8488.72300
            9      224.1119   1763.0290   290.96460   441.790300   176.94060

                           6            7            8            9   \
 time DIM_1 DIM_2
 1971 1     1       118.58520     22.20283     13.52112     2.419053
            2         0.00000      0.00000      0.00000     0.000000
            3         0.00000      0.00000      0.00000     0.000000
            4         0.00000      0.00000      0.00000     0.000000
            5         0.00000      0.00000      0.00000     0.000000
 ...                      ...          ...          ...          ...
 2100 4     5         0.00000      0.00000      0.00000     0.000000
            6        14.96734     18.91592    104.68340   158.921100
            7         0.00000      0.00000      0.00000     0.000000
            8      4826.07900  11260.52000  26553.81000  8595.178000
            9      1084.34000   1342.95100      6.53226  2073.331000

                           10  ...          19         20           21  \
 time DIM_1 DIM_2              ...
 1971 1     1      633.752400  ...   765.15890   5640.502    65.811830
            2        0.000000  ...     0.00000      0.000     0.000000
            3        0.000000  ...     0.00000      0.000     0.000000
            4        0.000000  ...     0.00000      0.000     0.000000
            5        0.000000  ...     0.00000      0.000     0.000000
 ...                      ...  ...         ...        ...          ...
 2100 4     5        0.000000  ...     0.00000      0.000     0.000000
            6        4.231123  ...    15.61917   1038.197     5.704651
            7        0.000000  ...     0.00000      0.000     0.000000
            8      949.804000  ...  2656.89200  18509.250  6846.668000
            9       83.335820  ...    52.52850   2716.567  1719.685000

                            22           23          24           25  \
 time DIM_1 DIM_2
 1971 1     1         7.268175   942.668800  264.554000     50.02193
            2         0.000000     0.000000    0.000000      0.00000
            3         0.000000     0.000000    0.000000      0.00000
            4         0.000000     0.000000    0.000000      0.00000
            5         0.000000     0.000000    0.000000      0.00000
 ...                       ...          ...         ...          ...
 2100 4     5         0.000000     0.000000    0.000000      0.00000
            6         6.048050     1.408716    4.130217     47.53690
            7         0.000000     0.000000    0.000000      0.00000
            8      3265.378000  1427.965000  895.222700  21198.22000
            9        35.103540   354.727100  209.903700    380.15480

                            26  27          28
 time DIM_1 DIM_2
 1971 1     1         79.75849 NaN   25757.080
            2          0.00000 NaN       0.000
            3          0.00000 NaN       0.000
            4          0.00000 NaN       0.000
            5          0.00000 NaN       0.000
 ...                       ...  ..         ...
 2100 4     5          0.00000 NaN       0.000
            6         47.51705 NaN    2752.434
            7          0.00000 NaN       0.000
            8      11885.22000 NaN  208764.300
            9       1562.05900 NaN   19425.760

 [4680 rows x 28 columns],
 'fossils_final': DIM_1                       1             2           3             4   \
 time DIM_3 DIM_2
 1971 1     1      1.885407e+02   2669.461000   48.014610  6.009494e+00
            2      1.949883e+00      0.011441    0.000417  7.702118e-05
            3      2.400606e+01    455.521200    0.000000  0.000000e+00
            4      9.603902e-24    238.706100    0.000000  2.963089e-18
            5      0.000000e+00    338.466400    0.000000  1.787177e-01
 ...                        ...           ...         ...           ...
 2100 4     5      4.376261e+01      0.000000    2.234597  1.253776e+00
            6      5.535803e+02   3717.186000   82.712380  4.233582e+02
            7      0.000000e+00      0.000000    0.000000  0.000000e+00
            8      0.000000e+00      0.000000    0.000000  0.000000e+00
            9      3.033570e+03  12059.370000  774.908600  7.069016e+02

 DIM_1                       5            6            7            8   \
 time DIM_3 DIM_2
 1971 1     1      2.717841e+01    79.054390    20.162060    10.038750
            2      4.327843e-01     7.239704     0.001923     3.418451
            3      0.000000e+00    26.878160     0.809236     0.063751
            4      2.662467e-44     0.746157     1.207115     0.000167
            5      0.000000e+00     2.766797     0.022500     0.000000
 ...                        ...          ...          ...          ...
 2100 4     5      2.193459e+01    16.197870    29.906540    63.097720
            6      4.964375e+02  1161.603000  1237.149000  1736.006000
            7      0.000000e+00     0.000000     0.000000     0.000000
            8      0.000000e+00     0.000000     0.000000     0.000000
            9      3.139136e+03  3994.328000  4963.359000  6894.896000

 DIM_1                      9           10  ...          19           20  \
 time DIM_3 DIM_2                           ...
 1971 1     1         0.541893  356.562700  ...  485.251100   3471.35700
            2         1.877074  134.812800  ...    1.202758    265.55210
            3         0.000000   72.921960  ...  151.679800   1482.37300
            4         0.000086   34.927050  ...    3.837449     49.42641
            5         0.000000    3.212520  ...  123.187900    371.79350
 ...                       ...         ...  ...         ...          ...
 2100 4     5       112.251300    7.040431  ...    8.664032     75.36282
            6       338.939000   57.151460  ...  420.291000   3951.94800
            7         0.000000    0.000000  ...    0.000000      0.00000
            8         0.000000    0.000000  ...    0.000000      0.00000
            9      5708.395000  794.667700  ...  995.500700  12791.82000

 DIM_1                      21           22            23           24  \
 time DIM_3 DIM_2
 1971 1     1        21.428080     5.921990  7.054720e+02   240.310100
            2         0.000000     1.284816  2.447403e+01     3.442993
            3         4.117115     0.000000  1.706647e+02    16.227480
            4         0.000039     0.000000  4.108063e+01     3.018469
            5        40.266600     0.061369  9.774001e-01     1.554935
 ...                       ...          ...           ...          ...
 2100 4     5        40.903930     7.109844  1.055176e-08     3.330146
            6       450.546200   135.144800  6.420629e+02   126.311500
            7         0.000000     0.000000  0.000000e+00     0.000000
            8         0.000000     0.000000  0.000000e+00     0.000000
            9      2177.187000  1656.494000  1.213750e+03  2167.464000

 DIM_1                       25           26   27          28
 time DIM_3 DIM_2
 1971 1     1      4.604663e+01    58.227680  0.0   14906.330
            2      8.600982e-03    11.548620  0.0    1429.008
            3      0.000000e+00     0.912527  0.0    5314.385
            4      1.482659e-37     4.831293  0.0    2260.924
            5      3.966704e+00     4.238370  0.0    1595.118
 ...                        ...          ...  ...         ...
 2100 4     5      9.003355e+00     3.895803  0.0     687.207
            6      1.867225e+03    27.911970  0.0   26204.240
            7      0.000000e+00     0.000000  0.0       0.000
            8      0.000000e+00     0.000000  0.0       0.000
            9      1.113595e+04  1800.644000  0.0  117103.000

 [4680 rows x 28 columns],
 'fossils_primary_converted': DIM_1                 1             2             3             4   \
 time DIM_2
 1971 1      2.415319e+10  4.333045e+11  2.164201e+09  2.114040e+08
 1972 1      2.136175e+10  4.688422e+11  2.421638e+09  2.163961e+08
 1973 1      2.399043e+10  5.014374e+11  2.625773e+09  1.973130e+08
 1974 1      2.452215e+10  4.875401e+11  2.775056e+09  1.817510e+08
 1975 1      2.206719e+10  4.798844e+11  3.117179e+09  1.714457e+08
 ...                  ...           ...           ...           ...
 2096 4      1.091600e+11  6.404893e+11  1.104707e+11  5.480877e+10
 2097 4      1.097427e+11  6.270105e+11  1.105574e+11  5.598163e+10
 2098 4      1.073653e+11  6.147858e+11  1.110472e+11  5.703864e+10
 2099 4      1.082691e+11  6.033889e+11  1.090580e+11  5.792337e+10
 2100 4      1.064567e+11  5.920324e+11  1.074965e+11  5.868579e+10

 DIM_1                 5             6             7             8   \
 time DIM_2
 1971 1      3.697284e+09  6.655450e+09  1.386091e+09  4.368484e+08
 1972 1      3.918945e+09  6.145810e+09  1.503261e+09  4.938156e+08
 1973 1      4.035125e+09  6.542837e+09  1.467221e+09  5.416114e+08
 1974 1      4.181467e+09  6.265446e+09  1.714362e+09  5.107104e+08
 1975 1      4.542197e+09  7.690024e+09  2.147746e+09  4.783145e+08
 ...                  ...           ...           ...           ...
 2096 4      2.739416e+11  2.006341e+11  3.794964e+11  8.501368e+11
 2097 4      2.729854e+11  2.038098e+11  3.702519e+11  8.627559e+11
 2098 4      2.694862e+11  2.063080e+11  3.606352e+11  8.737326e+11
 2099 4      2.663935e+11  2.096944e+11  3.534766e+11  8.764132e+11
 2100 4      2.639186e+11  2.127810e+11  3.472787e+11  8.718879e+11

 DIM_1                 9             10  ...            19            20  \
 time DIM_2                              ...
 1971 1      8.387405e+07  5.724391e+10  ...  3.268078e+10  2.184126e+11
 1972 1      5.031415e+07  5.971689e+10  ...  3.452167e+10  2.256562e+11
 1973 1      8.446443e+07  6.689097e+10  ...  3.809460e+10  2.283365e+11
 1974 1      9.769630e+07  6.991983e+10  ...  4.087446e+10  2.252545e+11
 1975 1      8.568848e+07  7.860173e+10  ...  4.399830e+10  2.606287e+11
 ...                  ...           ...  ...           ...           ...
 2096 4      2.329261e+11  3.081540e+10  ...  7.289425e+10  7.347241e+11
 2097 4      2.444533e+11  3.161059e+10  ...  7.247695e+10  7.231960e+11
 2098 4      2.562010e+11  3.250759e+10  ...  7.211580e+10  7.117383e+11
 2099 4      2.687672e+11  3.337408e+10  ...  7.180211e+10  7.017199e+11
 2100 4      2.805054e+11  3.427354e+10  ...  7.162862e+10  6.916360e+11

 DIM_1                 21            22            23            24  \
 time DIM_2
 1971 1      7.337519e+09  3.067338e+08  7.421149e+10  3.148874e+10
 1972 1      2.856830e+09  2.937782e+08  7.599723e+10  3.381372e+10
 1973 1      2.909851e+09  2.455166e+08  8.031498e+10  3.479187e+10
 1974 1      2.774400e+09  2.508008e+08  8.377249e+10  3.363942e+10
 1975 1      3.642318e+09  2.684527e+08  7.956626e+10  3.621910e+10
 ...                  ...           ...           ...           ...
 2096 4      2.242782e+11  1.240927e+11  5.536268e+10  7.886483e+10
 2097 4      2.211262e+11  1.225698e+11  5.472533e+10  7.844770e+10
 2098 4      2.166172e+11  1.210891e+11  5.406921e+10  7.834431e+10
 2099 4      2.125866e+11  1.193141e+11  5.346734e+10  7.742941e+10
 2100 4      2.084874e+11  1.176903e+11  5.290410e+10  7.710548e+10

 DIM_1                 25            26   27            28
 time DIM_2
 1971 1      1.803896e+09  3.721751e+09  0.0  2.060536e+12
 1972 1      1.785504e+09  3.595958e+09  0.0  2.076598e+12
 1973 1      1.769304e+09  3.873007e+09  0.0  2.196430e+12
 1974 1      1.702930e+09  3.801301e+09  0.0  2.213836e+12
 1975 1      1.796414e+09  3.291721e+09  0.0  2.210342e+12
 ...                  ...           ...  ...           ...
 2096 4      6.521552e+11  2.716299e+11  0.0  7.323324e+12
 2097 4      6.542370e+11  2.818261e+11  0.0  7.302648e+12
 2098 4      6.548351e+11  2.908056e+11  0.0  7.275632e+12
 2099 4      6.533785e+11  2.987013e+11  0.0  7.246414e+12
 2100 4      6.514467e+11  3.040193e+11  0.0  7.207862e+12

 [390 rows x 28 columns],
 'fossils_primsecond_converted':                             1             2             3             4   \
 time DIM_1 DIM_2
 1971 1     1      7.422031e+09  1.281026e+11  1.661420e+09  2.141276e+08
            2      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            3      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            4      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            5      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
 ...                        ...           ...           ...           ...
 2100 4     5      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            6      1.175331e+09  3.986414e+09  3.492261e+07  1.823486e+07
            7      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            8      8.436197e+09  3.024808e+11  6.847080e+10  3.438408e+10
            9      4.293331e+09  3.377450e+10  5.574034e+09  8.463416e+09

                             5             6             7             8   \
 time DIM_1 DIM_2
 1971 1     1      1.024769e+09  4.103294e+09  7.682640e+08  4.678588e+08
            2      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            3      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            4      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            5      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
 ...                        ...           ...           ...           ...
 2100 4     5      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            6      8.838879e+06  2.867307e+08  3.623739e+08  2.005429e+09
            7      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            8      1.626192e+11  9.245362e+10  2.157188e+11  5.086937e+11
            9      3.389667e+09  2.077280e+10  2.572703e+10  1.251391e+08

                             9             10  ...            19            20  \
 time DIM_1 DIM_2                              ...
 1971 1     1      8.370426e+07  2.192915e+10  ...  2.647609e+10  1.951731e+11
            2      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
            3      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
            4      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
            5      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
 ...                        ...           ...  ...           ...           ...
 2100 4     5      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
            6      3.044466e+09  8.105600e+07  ...  2.992178e+08  1.988883e+10
            7      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
            8      1.646586e+11  1.819548e+10  ...  5.089831e+10  3.545833e+11
            9      3.971898e+10  1.596472e+09  ...  1.006293e+09  5.204151e+10

                             21            22            23            24  \
 time DIM_1 DIM_2
 1971 1     1      2.277226e+09  2.514939e+08  3.261830e+10  9.154118e+09
            2      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            3      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            4      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            5      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
 ...                        ...           ...           ...           ...
 2100 4     5      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
            6      1.092845e+08  1.158630e+08  2.698690e+07  7.912293e+07

In [37]:
final_energy = read_mym_df(path_input_data.joinpath("SSP2_CP", 'EnergyFlows/final_energy_rt.out')).set_index(["time", "DIM_1", "DIM_2"])  
# final_energy = final_energy.T # transpose to make DIM_1 the index
# final_energy = final_energy.stack(['time', 'DIM_2'])  # add years as and DIM_2 index
# final_energy.index.names = ['DIM_3', 'time', 'DIM_2']
# final_energy = final_energy.swaplevel(0, 1)  # make years the first index

final_energy

                             1             2             3            4  \
time DIM_1 DIM_2
1971 1     1      1.885407e+02    378.652400      23.19438     465.6127
           2      1.949883e+00    150.974500    1035.98600       0.0000
           3      2.400606e+01    476.148100      75.83350     162.2789
           4      9.603902e-24    337.471200      11.36705     212.4781
           5      0.000000e+00     -0.316783      57.21869       0.0000
...                        ...           ...           ...          ...
2100 28    5      6.118241e+02    523.645000     339.24610     687.2070
           6      1.765552e+03      0.000000   25457.60000   26204.2400
           7      0.000000e+00      0.000000   60936.83000       0.0000
           8      0.000000e+00    252.625300     306.07770       0.0000
           9      1.758310e+04  31367.180000  120877.30000  117103.0000

                             5             6             7             8  \
time DIM_1 DIM_2
1971 1     1      2.412652e+02  0.000000e+00  0.000000e+00  0.000000e+00
           2      1.477286e-10  0.000000e+00  1.943009e-09  0.000000e+00
           3      0.000000e+00  6.000206e+01  0.000000e+00  0.000000e+00
           4      0.000000e+00  3.119263e-23  9.407405e-24  6.012254e-24
           5      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
...                        ...           ...           ...           ...
2100 28    5      2.955369e+03  6.186953e+01  9.432570e+00  2.575748e+01
           6      1.071213e+04  0.000000e+00  0.000000e+00  0.000000e+00
           7      2.999594e+03  0.000000e+00  1.853394e-04  0.000000e+00
           8      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
           9      5.050869e+04  1.355491e+04  1.596859e+03  2.995943e+03

                              9           10
time DIM_1 DIM_2
1971 1     1         347.450400    1644.7160
           2           7.740280    1196.6510
           3         129.779600     928.0482
           4         161.054800     722.3712
           5           6.566401      63.4683
...                         ...          ...
2100 28    5        8910.502000   14124.8500
           6           0.000000   64139.5200
           7           0.391718   63936.8200
           8         545.680700    1104.3840
           9      397971.500000  753558.6000

[32760 rows x 10 columns]

In [30]:
fossil_fuel_data.get("fossils_final_converteted").get('coal').loc[1971]

DIM_1                  1             2             3             4   \
DIM_3 DIM_2
1     1      6.523900e+09  9.236889e+10  1.661405e+09  2.079410e+08
      2      6.747000e+07  3.958775e+05  1.444133e+04  2.665093e+03
      3      8.306595e+08  1.576198e+10  0.000000e+00  0.000000e+00
      4      3.323149e-16  8.259727e+09  0.000000e+00  1.025290e-10
      5      0.000000e+00  1.171164e+10  0.000000e+00  6.184003e+06
      6      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      7      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      8      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      9      7.422031e+09  1.281026e+11  1.661420e+09  2.141276e+08

DIM_1                  5             6             7             8   \
DIM_3 DIM_2
1     1      9.404294e+08  2.735446e+09  6.976491e+08  3.473616e+08
      2      1.497524e+07  2.505088e+08  6.653021e+04  1.182855e+08
      3      0.000000e+00  9.300401e+08  2.800123e+07  2.205911e+06
      4      9.212689e-37  2.581857e+07  4.176869e+07  5.794969e+03
      5      0.000000e+00  9.573692e+07  7.785433e+05  0.000000e+00
      6      6.936439e+07  6.574391e+07  0.000000e+00  0.000000e+00
      7      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      8      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      9      1.024769e+09  4.103294e+09  7.682640e+08  4.678588e+08

DIM_1                  9             10  ...            17            18  \
DIM_3 DIM_2                              ...
1     1      1.875064e+07  1.233781e+10  ...  1.441893e+08  1.445195e+10
      2      6.495066e+07  4.664803e+09  ...  4.053048e+03  8.963436e+09
      3      0.000000e+00  2.523251e+09  ...  0.000000e+00  2.448484e+09
      4      2.972078e+03  1.208548e+09  ...  0.000000e+00  3.646433e+09
      5      0.000000e+00  1.111599e+08  ...  0.000000e+00  1.548697e+09
      6      0.000000e+00  1.083576e+09  ...  0.000000e+00  0.000000e+00
      7      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
      8      0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
      9      8.370426e+07  2.192915e+10  ...  1.441934e+08  3.105900e+10

DIM_1                  19            20            21            22  \
DIM_3 DIM_2
1     1      1.679070e+10  1.201162e+11  7.414561e+08  2.049131e+08
      2      4.161792e+07  9.188654e+09  0.000000e+00  4.445730e+07
      3      5.248436e+09  5.129318e+10  1.424607e+08  0.000000e+00
      4      1.327837e+08  1.710256e+09  1.338254e+03  0.000000e+00
      5      4.262557e+09  1.286483e+10  1.393308e+09  2.123487e+06
      6      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      7      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      8      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      9      2.647609e+10  1.951731e+11  2.277226e+09  2.514939e+08

DIM_1                  23            24            25            26
DIM_3 DIM_2
1     1      2.441080e+10  8.315228e+09  1.593309e+09  2.014799e+09
      2      8.468522e+08  1.191347e+08  2.976118e+05  3.996062e+08
      3      5.905353e+09  5.615045e+08  0.000000e+00  3.157532e+07
      4      1.421475e+09  1.044453e+08  5.130308e-30  1.671728e+08
      5      3.382007e+07  5.380398e+07  1.372562e+08  1.466564e+08
      6      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      7      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      8      0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
      9      3.261830e+10  9.154118e+09  1.730863e+09  2.759809e+09

[9 rows x 26 columns]